version: "3"
services:
  books-api:
    container_name: books-api
    restart: always
    build: .
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "4000:4000"
      - "9229:9229"
    networks:
      - booksAPI
    depends_on:
      - mongodb
    command:
      - npm
      - run
      - dev
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    command:
        - '--logpath' # sielent the log in the console and direct to file instead
        - '/var/log/mongodb/mongod.log'
    volumes:
      - D:/Workspace/Cap/skillsBooster/db:/data/db mongo
    ports:
      - "27017:27017"
    networks:
      - booksAPI
networks:
  booksAPI: